import streamlit as st
from itertools import combinations_with_replacement
from collections import Counter

# キャラクターごとの技データ
character_moves = {
    "ルーク": {
        "立ち弱ｐ": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 15, "cancel": 12, "is_chain": True, "last_additional": 2},
        "屈弱ｋ": {"normal": 18, "cancel": 14, "is_chain": True, "last_additional": 1},
        "屈中ｐ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "前中ｐ": {"normal": 43, "cancel": 43, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 37, "cancel": 37, "is_chain": False, "last_additional": 0},
        "引き強ｐ": {"normal": 48, "cancel": 48, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
    },
    "ジェイミー": {
        "立ち弱ｐ(酔いレベル0)": {"normal": 13, "cancel": 13, "is_chain": False, "last_additional": 0},
        "立ち弱ｐ(酔いレベル1以上)": {"normal": 16, "cancel": 16, "is_chain": False, "last_additional": 0},
        "立ち弱ｋ": {"normal": 17, "cancel": 13, "is_chain": True, "last_additional": 0},
        "立ち中P": {"normal": 25, "cancel": 25, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 17, "cancel": 13, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 43, "cancel": 43, "is_chain": False, "last_additional": 0},
        "前中ｋ": {"normal": 44, "cancel": 44, "is_chain": False, "last_additional": 0},
        "引き強ｐ": {"normal": 41, "cancel": 41, "is_chain": False, "last_additional": 0},
        "引き強ｐ(酔いレベル3以上)": {"normal": 42, "cancel": 42, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "天晴脚(↓+ K同時押し)": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},    
    },
    "マノン": {
        "立ち弱ｐ": {"normal": 16, "cancel": 13, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 25, "cancel": 25, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 43, "cancel": 43, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 16, "cancel": 13, "is_chain": True, "last_additional": 3},
        "屈弱ｋ": {"normal": 19, "cancel": 15, "is_chain": True, "last_additional": 2},
        "屈中ｐ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "引き強ｐ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "引き中ｋ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "前斜め強ｋ": {"normal": 51, "cancel": 51, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 21, "cancel": 21, "is_chain": False, "last_additional": 0},
    },
    "キンバリー": {
        "立ち弱ｐ": {"normal": 14, "cancel": 10, "is_chain": True, "last_additional": 0},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 31, "cancel": 31, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 13, "cancel": 10, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 14, "cancel": 10, "is_chain": True, "last_additional": 1},
        "屈中ｐ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 25, "cancel": 25, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "前斜め中ｋ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 50, "cancel": 50, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 42, "cancel": 42, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
    },
    "マリーザ": {
        "立ち弱ｐ": {"normal": 19, "cancel": 19, "is_chain": False, "last_additional": 0},
        "立ち弱ｋ": {"normal": 21, "cancel": 21, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "立ち強ｐ(溜めなし)": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "立ち強ｐ(最大溜め)": {"normal": 46, "cancel": 46, "is_chain": False, "last_additional": 0},
        "立ち強ｋ(溜めなし)": {"normal": 41, "cancel": 41, "is_chain": False, "last_additional": 0},
        "立ち強ｋ(最大溜め)": {"normal": 50, "cancel": 50, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 15, "cancel": 12, "is_chain": True, "last_additional": 0},
        "屈弱ｋ": {"normal": 19, "cancel": 15, "is_chain": True, "last_additional": 2},
        "屈中ｐ": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｐ(溜めなし)": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "屈強ｐ(最大溜め)": {"normal": 47, "cancel": 47, "is_chain": False, "last_additional": 0},
        "屈強ｋ(溜めなし)": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "屈強ｋ(最大溜め)": {"normal": 45, "cancel": 45, "is_chain": False, "last_additional": 0},
        "前中ｐ": {"normal": 31, "cancel": 31, "is_chain": False, "last_additional": 0},
        "前斜め強ｐ(溜めなし)": {"normal": 43, "cancel": 43, "is_chain": False, "last_additional": 0},
        "前斜め強ｐ(最大溜め)": {"normal": 48, "cancel": 48, "is_chain": False, "last_additional": 0},
        "引き強ｐ(溜めなし)": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},
        "引き強ｐ(最大溜め)": {"normal": 45, "cancel": 45, "is_chain": False, "last_additional": 0},
        "前強ｋ(溜めなし)": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "前強ｋ(最大溜め)": {"normal": 49, "cancel": 49, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
    },
    "リリー": {
        "立ち弱ｐ": {"normal": 15, "cancel": 11, "is_chain": True, "last_additional": 0},
        "立ち弱ｋ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 1},
        "立ち中P": {"normal": 25, "cancel": 25, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 17, "cancel": 13, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 44, "cancel": 44, "is_chain": False, "last_additional": 0},
        "前斜め強ｐ": {"normal": 45, "cancel": 45, "is_chain": False, "last_additional": 0},
        "引き強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 41, "cancel": 41, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 21, "cancel": 21, "is_chain": False, "last_additional": 0},
    },
    "JP": {
        "立ち弱ｐ": {"normal": 18, "cancel": 13, "is_chain": True, "last_additional": 0},
        "立ち弱ｋ": {"normal": 18, "cancel": 14, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 16, "cancel": 13, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 17, "cancel": 12, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},
        "引き中ｐ": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "前斜め強ｐ": {"normal": 49, "cancel": 49, "is_chain": False, "last_additional": 0},
        "前中ｋ": {"normal": 42, "cancel": 42, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 40, "cancel": 40, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
    },
    "ジュリ": {
        "立ち弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 16, "cancel": 16, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 21, "cancel": 21, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 15, "cancel": 11, "is_chain": True, "last_additional": -2},
        "屈中ｐ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "前中ｐ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 45, "cancel": 45, "is_chain": False, "last_additional": 0},
        "前中ｋ": {"normal": 45, "cancel": 45, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 40, "cancel": 40, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
    },
    "ディージェイ": {
        "立ち弱ｐ": {"normal": 12, "cancel": 9, "is_chain": True, "last_additional": 0},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 40, "cancel": 40, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 15, "cancel": 11, "is_chain": True, "last_additional": 0},
        "屈弱ｋ": {"normal": 16, "cancel": 12, "is_chain": True, "last_additional": 1},
        "屈中ｐ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "前中ｋ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 19, "cancel": 19, "is_chain": False, "last_additional": 0},
    },
    "キャミィ": {
        "立ち弱ｐ": {"normal": 13, "cancel": 10, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 17, "cancel": 17, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 13, "cancel": 10, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 14, "cancel": 10, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "引き中ｐ": {"normal": 21, "cancel": 21, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 45, "cancel": 45, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
    },
    "リュウ": {
        "立ち弱ｐ": {"normal": 13, "cancel": 9, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 20, "cancel": 20, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 12, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 16, "cancel": 12, "is_chain": False, "last_additional": 0},
        "屈中ｐ": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "前中ｐ": {"normal": 42, "cancel": 42, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 40, "cancel": 40, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "引き強ｐ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 44, "cancel": 44, "is_chain": False, "last_additional": 0},
    },
    "エドモンド本田": {
        "立ち弱ｐ": {"normal": 17, "cancel": 17, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 14, "cancel": 14, "is_chain": False, "last_additional": 0},	
        "立ち中P": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 16, "cancel": 13, "is_chain": True, "last_additional": 3},
        "屈弱ｋ": {"normal": 15, "cancel": 11, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 37, "cancel": 37, "is_chain": False, "last_additional": 0},
        "前斜め強ｋ": {"normal": 45, "cancel": 45, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 19, "cancel": 19, "is_chain": False, "last_additional": 0},
    },
    "ブランカ": {
        "立ち弱ｐ": {"normal": 17, "cancel": 17, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 14, "cancel": 11, "is_chain": False, "last_additional": 2},
        "立ち中P": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 16, "cancel": 11, "is_chain": True, "last_additional": 0},
        "屈弱ｋ": {"normal": 16, "cancel": 12, "is_chain": True, "last_additional": 1},
        "屈中ｐ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 37, "cancel": 37, "is_chain": False, "last_additional": 0},
        "前中ｐ": {"normal": 42, "cancel": 42, "is_chain": False, "last_additional": 0},
        "前中ｋ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "引き中ｋ": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 52, "cancel": 52, "is_chain": False, "last_additional": 0},
        "前斜め強ｐ": {"normal": 45, "cancel": 45, "is_chain": False, "last_additional": 0},
        "サプライズフォワード": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "サプライズバック": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 19, "cancel": 19, "is_chain": False, "last_additional": 0},
    },
    "ガイル": {
        "立ち弱ｐ": {"normal": 14, "cancel": 10, "is_chain": True, "last_additional": 0},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 0},
        "屈弱ｋ": {"normal": 18, "cancel": 14, "is_chain": True, "last_additional": 2},
        "屈中ｐ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 50, "cancel": 50, "is_chain": False, "last_additional": 0},
        "前中ｐ": {"normal": 41, "cancel": 41, "is_chain": False, "last_additional": 0},
        "引き強ｐ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "引き弱ｋ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "前または引き中ｋ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 45, "cancel": 45, "is_chain": False, "last_additional": 0},
        "前斜め強ｋ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 21, "cancel": 21, "is_chain": False, "last_additional": 0},
    },
    "ケン": {
        "立ち弱ｐ": {"normal": 13, "cancel": 10, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 31, "cancel": 31, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 17, "cancel": 13, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "奮迅弱派生(最速入力)": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 19, "cancel": 19, "is_chain": False, "last_additional": 0},
    },
    "春麗": {
        "立ち弱ｐ": {"normal": 13, "cancel": 9, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 17, "cancel": 17, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 13, "cancel": 10, "is_chain": True, "last_additional": 0},
        "屈弱ｋ": {"normal": 15, "cancel": 12, "is_chain": False, "last_additional": 1},
        "屈中ｐ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 41, "cancel": 41, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},
        "前または引き中ｐ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "前斜め強ｐ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 40, "cancel": 40, "is_chain": False, "last_additional": 0},
        "前斜め強ｋ": {"normal": 51, "cancel": 51, "is_chain": False, "last_additional": 0},
        "引き強ｐ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
    },
    "ザンギエフ": {
        "立ち弱ｐ": {"normal": 15, "cancel": 9, "is_chain": True, "last_additional": 0},
        "立ち弱ｋ": {"normal": 25, "cancel": 25, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "立ち強ｐ(溜めなし)": {"normal": 42, "cancel": 42, "is_chain": False, "last_additional": 0},
        "立ち強ｐ(最大溜め)": {"normal": 58, "cancel": 58, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 37, "cancel": 37, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 12, "cancel": 7, "is_chain": True, "last_additional": 0},
        "屈弱ｋ": {"normal": 17, "cancel": 14, "is_chain": True, "last_additional": 4},
        "屈中ｐ": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 42, "cancel": 42, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 41, "cancel": 41, "is_chain": False, "last_additional": 0},
        "前斜め中ｐ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "前中ｋ": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 53, "cancel": 53, "is_chain": False, "last_additional": 0},
        "前斜め強ｋ": {"normal": 59, "cancel": 59, "is_chain": False, "last_additional": 0},
        "ストンピング１段目(↓↓+中ｋ)": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "ストンピング２段目(↓↓+中ｋ)": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "ストンピング３段目(↓↓+中ｋ)": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
    },
    "ダルシム": {
        "立ち弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": -1},
        "立ち弱ｋ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 46, "cancel": 46, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 16, "cancel": 12, "is_chain": True, "last_additional": 0},
        "屈弱ｋ": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "屈中ｐ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 46, "cancel": 46, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 47, "cancel": 47, "is_chain": False, "last_additional": 0},
        "引き中ｐ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "引き強ｐ": {"normal": 49, "cancel": 49, "is_chain": False, "last_additional": 0},
        "後ろ斜め強ｐ": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},
        "後ろ斜め弱ｋ": {"normal": 17, "cancel": 17, "is_chain": False, "last_additional": 0},
        "引き中ｋ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "後ろ斜め中ｋ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "後ろ斜め強ｋ": {"normal": 33, "cancel": 33, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 25, "cancel": 25, "is_chain": False, "last_additional": 0},
    },
    "ラシード": {
        "立ち弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 16, "cancel": 16, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 10, "is_chain": True, "last_additional": -1},
        "屈弱ｋ": {"normal": 15, "cancel": 11, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 22, "cancel": 22, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 37, "cancel": 37, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "前中ｐ": {"normal": 43, "cancel": 43, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 45, "cancel": 45, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 42, "cancel": 42, "is_chain": False, "last_additional": 0},
        "サイドフリップ１段目": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
    },
    "A.K.I": {
        "立ち弱ｐ": {"normal": 13, "cancel": 13, "is_chain": False, "last_additional": 0},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 31, "cancel": 31, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 2},
        "屈弱ｋ": {"normal": 15, "cancel": 11, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 25, "cancel": 25, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 40, "cancel": 40, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "前斜め中ｐ": {"normal": 44, "cancel": 44, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "前強ｋ": {"normal": 48, "cancel": 48, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 19, "cancel": 19, "is_chain": False, "last_additional": 0},
    },
    "ED": {
        "立ち弱ｐ": {"normal": 13, "cancel": 9, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 20, "cancel": 20, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 31, "cancel": 31, "is_chain": False, "last_additional": 0},
        "立ち強ｐ(溜めなし)": {"normal": 31, "cancel": 31, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 16, "cancel": 16, "is_chain": True, "last_additional": 3},
        "屈弱ｋ": {"normal": 18, "cancel": 18, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 37, "cancel": 37, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 40, "cancel": 40, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 19, "cancel": 19, "is_chain": False, "last_additional": 0},
    },
    "豪鬼": {
        "立ち弱ｐ": {"normal": 13, "cancel": 10, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 20, "cancel": 20, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 31, "cancel": 31, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 43, "cancel": 43, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 16, "cancel": 12, "is_chain": True, "last_additional": 1},
        "屈中ｐ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "前中ｐ": {"normal": 42, "cancel": 42, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "前中ｋ": {"normal": 31, "cancel": 31, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 43, "cancel": 43, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 19, "cancel": 19, "is_chain": False, "last_additional": 0},
    },
    "ベガ": {
        "立ち弱ｐ": {"normal": 17, "cancel": 13, "is_chain": True, "last_additional": 2},
        "立ち弱ｋ": {"normal": 15, "cancel": 15, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 25, "cancel": 25, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 41, "cancel": 41, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 15, "cancel": 12, "is_chain": True, "last_additional": 2},
        "屈弱ｋ": {"normal": 16, "cancel": 12, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 25, "cancel": 25, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 44, "cancel": 44, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "前斜め強ｋ": {"normal": 47, "cancel": 47, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 19, "cancel": 19, "is_chain": False, "last_additional": 0},
    },
    "テリー": {
        "立ち弱ｐ": {"normal": 13, "cancel": 9, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 25, "cancel": 25, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 10, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 17, "cancel": 13, "is_chain": False, "last_additional": 0},
        "屈中ｐ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 43, "cancel": 43, "is_chain": False, "last_additional": 0},
    },
    "舞": {
        "立ち弱ｐ": {"normal": 13, "cancel": 11, "is_chain": True, "last_additional": 1},
        "立ち弱ｋ": {"normal": 14, "cancel": 14, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 13, "cancel": 10, "is_chain": True, "last_additional": 0},
        "屈弱ｋ": {"normal": 15, "cancel": 11, "is_chain": True, "last_additional": 0},
        "屈中ｐ": {"normal": 26, "cancel": 26, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 28, "cancel": 28, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 41, "cancel": 41, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "前中ｐ": {"normal": 40, "cancel": 40, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 32, "cancel": 32, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
    },
    "エレナ": {
        "立ち弱ｐ": {"normal": 16, "cancel": 16, "is_chain": False, "last_additional": 0},
        "立ち弱ｋ": {"normal": 18, "cancel": 18, "is_chain": False, "last_additional": 0},
        "立ち中P": {"normal": 27, "cancel": 27, "is_chain": False, "last_additional": 0},
        "立ち中ｋ": {"normal": 24, "cancel": 24, "is_chain": False, "last_additional": 0},
        "立ち強ｐ": {"normal": 35, "cancel": 35, "is_chain": False, "last_additional": 0},
        "立ち強ｋ": {"normal": 34, "cancel": 34, "is_chain": False, "last_additional": 0},
        "屈弱ｐ": {"normal": 14, "cancel": 11, "is_chain": True, "last_additional": 1},
        "屈弱ｋ": {"normal": 15, "cancel": 11, "is_chain": True, "last_additional": 1},
        "屈中ｐ": {"normal": 30, "cancel": 30, "is_chain": False, "last_additional": 0},
        "屈中ｋ": {"normal": 29, "cancel": 29, "is_chain": False, "last_additional": 0},
        "屈強ｐ": {"normal": 38, "cancel": 38, "is_chain": False, "last_additional": 0},
        "屈強ｋ": {"normal": 37, "cancel": 37, "is_chain": False, "last_additional": 0},
        "前強ｐ": {"normal": 39, "cancel": 39, "is_chain": False, "last_additional": 0},
        "前中ｋ": {"normal": 41, "cancel": 41, "is_chain": False, "last_additional": 0},
        "前斜め強ｋ": {"normal": 44, "cancel": 44, "is_chain": False, "last_additional": 0},
        "引き強ｋ": {"normal": 36, "cancel": 36, "is_chain": False, "last_additional": 0},
        "通常投げ": {"normal": 23, "cancel": 23, "is_chain": False, "last_additional": 0},
        "前方ステップ": {"normal": 20, "cancel": 20, "is_chain": False, "last_additional": 0},
    }
}

# 技フレーム計算ロジック
def compute_combo_total(combo, move_data):
    usage_tracker = Counter()
    total = 0
    detail = []

    for move in combo:
        usage_tracker[move] += 1
        count = usage_tracker[move]
        move_info = move_data[move]

        if move_info["is_chain"]:
            total_count = combo.count(move)
            if total_count == 1:
                frame = move_info["normal"]
                label = "N"
            else:
                if count == 1:
                    frame = move_info["normal"]
                    label = "N"
                elif count < total_count:
                    frame = move_info["cancel"]
                    label = "C"
                else:
                    frame = move_info["cancel"] + move_info["last_additional"]
                    label = f"C+{move_info['last_additional']}"
        else:
            frame = move_info["normal"]
            label = "N"

        total += frame
        detail.append((move, label))

    return total, detail

# コンボ検索
def find_frame_combos(move_data, target, tolerance=1):
    move_names = list(move_data.keys())
    results = []

    for r in range(1, 4):
        for combo in combinations_with_replacement(move_names, r):
            total, detail = compute_combo_total(combo, move_data)

            invalid = False
            for move in set(combo):
                if move_data[move]["is_chain"] and combo.count(move) > 1:
                    tags = [t for m, t in detail if m == move]
                    if all(t == "N" for t in tags):
                        invalid = True
                        break
            if invalid:
                continue

            if abs(total - target) <= tolerance:
                formatted = [f"{m}({t})" for m, t in detail]
                results.append((formatted, total))

    return sorted(results, key=lambda x: abs(x[1] - target))

# ==== Streamlit GUI ====

st.title("ストリートファイター6 技フレーム消費検索")
selected_char = st.selectbox("キャラクターを選択", list(character_moves.keys()))
target_frame = st.number_input(f"{selected_char}で消費したいフレーム数を入力", min_value=1, max_value=300, step=1)

if st.button("検索"):
    results = find_frame_combos(character_moves[selected_char], target_frame)
    if results:
        st.success(f"見つかった組み合わせ（上位5件）:")
        for detail, total in results[:5]:
            st.write(f"{' + '.join(detail)} = {total}F")
    else:
        st.warning("該当する技の組み合わせが見つかりませんでした。")
